### ISSUE TITLE
Feature and bugs

### ISSUE THREAD

**Issue by mhwasil** [DigiKlausur/ilias2nbgrader#8]
1. [Feature] Add zip extraction in the student dir in case students only submitted zip file
2. ~~[Bug] It does not copy source file if there is no ipynb file in the submission.~~ will reopen later if the issue persists
    * I have submission directory which only has pdf inside, it gives me an error when converting to nbgrader submission

**Comment by tmetzl** [comment]
Feature has been implemented.
Bug is not reproducible for me. Please comment if it persists.
